import { Router } from 'express';
import { acceptCall, activeCalls, callSignals, callStream, connectedPeople, createGroupChat, declineCall, deleteGroupChatMessage, deleteMessage, downloadCallRecording, editGroupChatMessage, editMessage, endCall, getGroupChatMessages, getMessages, leaveGroupChat, listGroupChats, pinGroupChatMessage, pinMessage, sendCallSignal, sendGroupChatMessage, sendMessage, startCall, toggleGroupModerator, updateGroupChat, uploadCallRecording } from '../controllers/messageController.js';
import { requireAuth } from '../middleware/auth.js';

export const messageRoutes = Router();

messageRoutes.get('/connected/people', requireAuth, connectedPeople);
messageRoutes.get('/calls/stream', callStream);
messageRoutes.get('/calls/active', requireAuth, activeCalls);
messageRoutes.post('/calls', requireAuth, startCall);
messageRoutes.post('/calls/:callId/accept', requireAuth, acceptCall);
messageRoutes.post('/calls/:callId/decline', requireAuth, declineCall);
messageRoutes.post('/calls/:callId/end', requireAuth, endCall);
messageRoutes.get('/calls/:callId/signals', requireAuth, callSignals);
messageRoutes.post('/calls/:callId/signals', requireAuth, sendCallSignal);
messageRoutes.post('/calls/:callId/recording', requireAuth, uploadCallRecording);
messageRoutes.get('/calls/:callId/recording', requireAuth, downloadCallRecording);
messageRoutes.get('/group-chats', requireAuth, listGroupChats);
messageRoutes.post('/group-chats', requireAuth, createGroupChat);
messageRoutes.get('/group-chats/:groupChatId', requireAuth, getGroupChatMessages);
messageRoutes.patch('/group-chats/:groupChatId', requireAuth, updateGroupChat);
messageRoutes.post('/group-chats/:groupChatId/leave', requireAuth, leaveGroupChat);
messageRoutes.post('/group-chats/:groupChatId/moderators/:userId', requireAuth, toggleGroupModerator);
messageRoutes.patch('/group-chats/messages/:messageId', requireAuth, editGroupChatMessage);
messageRoutes.delete('/group-chats/messages/:messageId', requireAuth, deleteGroupChatMessage);
messageRoutes.patch('/group-chats/messages/:messageId/pin', requireAuth, pinGroupChatMessage);
messageRoutes.post('/group-chats/:groupChatId', requireAuth, sendGroupChatMessage);
messageRoutes.patch('/items/:messageId', requireAuth, editMessage);
messageRoutes.delete('/items/:messageId', requireAuth, deleteMessage);
messageRoutes.patch('/items/:messageId/pin', requireAuth, pinMessage);
messageRoutes.get('/:matchId', requireAuth, getMessages);
messageRoutes.post('/:matchId', requireAuth, sendMessage);
